In [1]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")

144
170
164
167
177


In [2]:
import numpy as np

In [5]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69,78,72,91,75])
student2:ndarray = np.array([75,92,92,76,92])

#可以做陣列運算,不須使用for...in
totols:ndarray= student1 + student2
for totol in totols:
    print(totol)
    print('=======')

144
170
164
167
167


In [9]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [6]:
np.random.randint(50,101,size=(50,5))

array([[ 59,  94,  56,  60,  50],
       [ 53,  85,  59,  50,  97],
       [ 93,  96,  87,  86,  71],
       [ 89,  94,  87,  78,  98],
       [ 65,  68,  72,  95,  91],
       [ 65,  51,  60,  79,  53],
       [ 75,  60,  82,  89,  97],
       [ 70,  76,  92,  75,  76],
       [ 91,  78,  75,  78,  79],
       [ 84,  97,  88,  89,  87],
       [ 70,  64,  72,  93,  73],
       [ 83,  97,  60,  56,  97],
       [ 59,  99,  99,  79,  53],
       [ 83,  96,  72,  66,  81],
       [ 59,  86,  53,  80,  73],
       [ 50,  96,  62,  70,  90],
       [ 90, 100,  99,  50,  80],
       [ 76,  79,  54,  70, 100],
       [ 57,  96,  67,  52,  64],
       [ 87,  59,  80,  77,  93],
       [ 51, 100,  75,  88,  98],
       [ 77,  73,  69,  92,  98],
       [ 81,  96,  76,  85,  62],
       [ 65,  82,  81,  76,  62],
       [ 76,  50,  82,  84,  59],
       [ 95,  94,  52, 100,  94],
       [ 61,  67,  96,  54,  51],
       [ 93,  63,  65,  99,  57],
       [ 72,  80,  61,  50,  55],
       [ 73,  